### ISSUE TITLE
Joint following error on larger file

### ISSUE THREAD

**Issue by pauloasherring** [machinekit/machinekit-cnc#52] opened 2018-10-02 03:47 UTC
Hi there! I most certainly don't know this is the right place for it, if it isn't, I apologize in advance.
I am running machinekit remote, mkwrapper as DISPLAY, along with cetus interface as remote interface, on a BeagleBone Green, rt-preempt on a 4.4 kernel, most recent  (as of 10/2/2018) apt-get available machinekit release, latest machinekit client release.
I am having issue with joint following errors.
It happens if I go any further on a given long ngc file. If I reduce a lot the feed rate (from 1800 mm/min to 600 mm/m), it doesn't happen.
Tried varying servo thread period and reducing stepgen period, without success.
If I execute the exact same a remote X session over ssh and the axis front end, I get no problems.
Is there a way for me to debug this issue any further?
Thanks!
Paulo Sherring.

**Comment by ArcEye** [comment] 2018-10-02 09:39
It is almost certainly because you are using Cetus and remote interface.

Please cut and paste into an issue here https://github.com/machinekit/Cetus/issues
and close this one

**Comment by pauloasherring** [comment] 2018-10-02 13:53
Will do, thanks!

**Comment by pauloasherring** [comment] 2018-10-02 15:21
I guess it is unrelated to the remote UI. I tried Machineface and had the same problem. Also tried local UI, by loading it from Machinekil Client. 
While trying to debug the issue, i figured out that running halmeter cleared the joint following error. I am guessing that there is something goind NOK with my configuration + mkwrapper. Should i really close this?
I don't know how I could use this as workaround - running halmeter -, since my intention is to it Xorg-less.

**Comment by ArcEye** [comment] 2018-10-02 16:20
> I guess it is unrelated to the remote UI. I tried Machineface and had the same problem.

Both of which are remote UIs and not included in this repo

> If I execute the exact same a remote X session over ssh and the axis front end, I get no problems.

So the problem is with the remote running using MachinekitClient / mkwrapper / Cetus / Machineface

The only person who knows much about those is the one who wrote them and I have allocated the issue to him.

I would suggest however that you make an entry there, actually saying what machine you are running, linking to the config, the code etc. etc.

**Closed by ArcEye** 2018-10-02 16:20 UTC
